### ISSUE TITLE
Keep shared broadcasted dimensions with binary operations

### ISSUE THREAD

**Issue by coreylowman** [coreylowman/dfdx#366]
This is an optimization that further minimizes the amount of data needed for certain cases of binary operations.

For example if you add two tensors that both have the 0th dimension broadcasted, the output tensor can also have the 0th dimension broadcasted.

Generally it seems like any dimension that both tensors have broadcasted can also be broadcasted in the output.

For some reason it doesn't seem like pytorch does this, so we should investigate why they don't (search around in issues for something like this).

See conversation in: _Originally posted by @nkoppel in https://github.com/coreylowman/dfdx/pull/363#discussion_r1071482157_

**Comment by nkoppel** [comment]
I haven't been able to find anything specifically about this, but I think that pytorch is unable to do this because its tensors are mutable and because of pythons lack of aliasing rules. Consider the following example:
```python
>>> a = torch.randn(2, 3)
>>> b = torch.randn(5,2, 3)
>>> a2 = a.broadcast_to(5, 2, 3)
>>> c = a2
>>> a2 += b
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
RuntimeError: unsupported operation: more than one element of the written-to tensor refers to a single memory location. Please clone() the tensor before performing the operation.
>>> a2.add_(b)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
RuntimeError: unsupported operation: more than one element of the written-to tensor refers to a single memory location. Please clone() the tensor before performing the operation.
```
An apparent solution to the error above would be to have pytorch create a new tensor without broadcasting and store that back into a2, but doing this will not update c, which is unexpected. So pytorch probably has to keep its tensors unbroadcasted as much as possible to keep their api usable. Due to rust's protections against shared mutation, this will never be a problem for this library, even if we make our tensors mutable.

**Comment by coreylowman** [comment]
Hmm interesting observation. It seems like ref count the tensors thought, so they could detect if only one tensor refers to it and broadcast it then? It could also be to prevent the need for atomicAdds in backwards (or simplicity cause I guess you can avoid this if you're smart)?

I'm also trying to think when this case would even come up (when tensors have same dimensions broadcasted) naturally... can you think of any situations when it happens? Could just be that its not worth the added code complexity

**Comment by nkoppel** [comment]
Yeah, I can't really think of an organic use case for this, so I guess we should put this on the back burner until a user needs this functionality.
